// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Modifier is an autogenerated mock type for the Modifier type
type Modifier[T interface{}] struct {
	mock.Mock
}

type Modifier_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Modifier[T]) EXPECT() *Modifier_Expecter[T] {
	return &Modifier_Expecter[T]{mock: &_m.Mock}
}

// Enabled provides a mock function with given fields:
func (_m *Modifier[T]) Enabled() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Modifier_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type Modifier_Enabled_Call[T interface{}] struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *Modifier_Expecter[T]) Enabled() *Modifier_Enabled_Call[T] {
	return &Modifier_Enabled_Call[T]{Call: _e.mock.On("Enabled")}
}

func (_c *Modifier_Enabled_Call[T]) Run(run func()) *Modifier_Enabled_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Modifier_Enabled_Call[T]) Return(_a0 bool) *Modifier_Enabled_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

// Modify provides a mock function with given fields: _a0
func (_m *Modifier[T]) Modify(_a0 *T) {
	_m.Called(_a0)
}

// Modifier_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type Modifier_Modify_Call[T interface{}] struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - _a0 *T
func (_e *Modifier_Expecter[T]) Modify(_a0 interface{}) *Modifier_Modify_Call[T] {
	return &Modifier_Modify_Call[T]{Call: _e.mock.On("Modify", _a0)}
}

func (_c *Modifier_Modify_Call[T]) Run(run func(_a0 *T)) *Modifier_Modify_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *Modifier_Modify_Call[T]) Return() *Modifier_Modify_Call[T] {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewModifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewModifier creates a new instance of Modifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewModifier[T interface{}](t mockConstructorTestingTNewModifier) *Modifier[T] {
	mock := &Modifier[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
