// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// scalarType is an autogenerated mock type for the scalarType type
type scalarType struct {
	mock.Mock
}

type scalarType_Expecter struct {
	mock *mock.Mock
}

func (_m *scalarType) EXPECT() *scalarType_Expecter {
	return &scalarType_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTnewScalarType interface {
	mock.TestingT
	Cleanup(func())
}

// newScalarType creates a new instance of scalarType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newScalarType(t mockConstructorTestingTnewScalarType) *scalarType {
	mock := &scalarType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
