// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// envModifier is an autogenerated mock type for the envModifier type
type envModifier struct {
	mock.Mock
}

type envModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *envModifier) EXPECT() *envModifier_Expecter {
	return &envModifier_Expecter{mock: &_m.Mock}
}

// getEnvs provides a mock function with given fields:
func (_m *envModifier) getEnvs() []v1.EnvVar {
	ret := _m.Called()

	var r0 []v1.EnvVar
	if rf, ok := ret.Get(0).(func() []v1.EnvVar); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.EnvVar)
		}
	}

	return r0
}

// envModifier_getEnvs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getEnvs'
type envModifier_getEnvs_Call struct {
	*mock.Call
}

// getEnvs is a helper method to define mock.On call
func (_e *envModifier_Expecter) getEnvs() *envModifier_getEnvs_Call {
	return &envModifier_getEnvs_Call{Call: _e.mock.On("getEnvs")}
}

func (_c *envModifier_getEnvs_Call) Run(run func()) *envModifier_getEnvs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *envModifier_getEnvs_Call) Return(_a0 []v1.EnvVar) *envModifier_getEnvs_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTnewEnvModifier interface {
	mock.TestingT
	Cleanup(func())
}

// newEnvModifier creates a new instance of envModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newEnvModifier(t mockConstructorTestingTnewEnvModifier) *envModifier {
	mock := &envModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
